name: tubes_mobile
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-210.4.beta <4.0.0'



dependencies:
  flutter:
    sdk: flutter


#------------------------------ PACKAGES ----------------------------------#
  # Utility Packaages
  
  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  
  # State Management
  get: ^4.6.6
  url_launcher: ^6.2.2
  intl: ^0.19.0
  http: ^1.1.0
  get_storage: ^2.1.1
  logger: ^2.0.2+1
  flutter_native_splash: ^2.3.7
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1

  # Product Spesific

#------------------------------ / PACKAGES END ----------------------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  #------------------------------ LOCAL ASSETS ----------------------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/reviews/
    - assets/images/content/
    - assets/images/products/
    - assets/images/banners/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/icons/payment_methods/
  
  #------------------------------ LOCAL ASSETS ----------------------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins-Light.ttf
          weight: 300
        - asset: assets\fonts\Poppins-Regular.ttf
          weight: 400
        - asset: assets\fonts\Poppins-Italic.ttf
          style: italic
        - asset: assets\fonts\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets\fonts\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 600